### ISSUE TITLE
This doesn't work

### ISSUE THREAD

**Issue by proevilz** [TwilioDevEd/conversations-demo#32]
I place my key in the app, and the 'open conversations' box just spins. 

What is this app supposed to do exactly?

**Comment by floofydoug** [comment]
Same thing happened to me on the sandbox. Connection is good, but app just spins. 

![image](https://user-images.githubusercontent.com/1750326/115797441-c9b69d00-a388-11eb-886e-780ac619002b.png)

**Comment by floofydoug** [comment]
I did some searching online and found an earlier iteration demo of this repo with instructions on how to get started with conversations: 

https://www.youtube.com/watch?v=jKlv_8YFg2g

Basically, you will need to: 

1. create a conversation in the dashboard, if you haven't already. 
 ```twilio api:conversations:v1:conversations:participants:create --conversation-sid <your sid> ```

2. create a participant and add them to the conversation: 
```twilio api:conversations:v1:conversations:participants:create --conversation-sid <your chat sid>  --identity floofydoug```

3. use the same identity logging in as the identity provided to see the conversations they're a part of.

**Comment by RPGillespie6** [comment]
The key for me was making sure the access token I generated used an `--identity` that matched an existing participant in the specified chat service

**Comment by jefflinwood** [comment]
I added a link in the README to the Conversations Quickstart - that has a walkthrough, including the steps above that involve adding a participant to the conversation. Thanks!

https://www.twilio.com/docs/conversations/quickstart
